/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('movies').del()
  await knex('movies').insert([
      {
        "backdrop_path": "/hYZ4a0JvPETdfgJJ9ZzyFufq8KQ.jpg",
        "tmdbid": 629176,
        "title": "Samaritan",
        "original_language": "en",
        "overview": "Thirteen year old Sam Cleary  suspects that his mysteriously reclusive neighbor Mr. Smith is actually the legendary vigilante Samaritan, who was reported dead 20 years ago. With crime on the rise and the city on the brink of chaos, Sam makes it his mission to coax his neighbor out of hiding to save the city from ruin.",
        "poster_path": "/zgH8Ej50n2cvJCMJrxd4twEwSqz.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          28,
          18,
          878,
          14
        ]),
        "popularity": "686.637",
        "release_date": "2022-08-25",
        "vote_average": 6.695,
        "vote_count": 275,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/9n5e1vToDVnqz3hW10Jdlvmzpo0.jpg",
        "tmdbid": 361743,
        "title": "Top Gun: Maverick",
        "original_language": "en",
        "overview": "After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.",
        "poster_path": "/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          28,
          18
        ]),
        "popularity": "4724.785",
        "release_date": "2022-05-24",
        "vote_average": 8.374,
        "vote_count": 3002,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/Aa9TLpNpBMyRkD8sPJ7ACKLjt0l.jpg",
        "tmdbid": 94997,
        "title": "House of the Dragon",
        "original_language": "en",
        "overview": "The prequel series finds the Targaryen dynasty at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires—real and imagined—crumble from such heights. In the case of the Targaryens, their slow fall begins almost 193 years before the events of Game of Thrones, when King Viserys Targaryen breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.",
        "poster_path": "/z2yahl2uefxDCl0nogcRBstwruJ.jpg",
        "media_type": "tv",
        "genre_ids": JSON.stringify([
          18,
          10759,
          10765
        ]),
        "popularity": "7964.892",
        "vote_average": 8.855,
        "vote_count": 605,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/lbLPVvgq16BD3IA6sIH3riu9ouO.jpg",
        "tmdbid": 762504,
        "title": "Nope",
        "original_language": "en",
        "overview": "Residents in a lonely gulch of inland California bear witness to an uncanny, chilling discovery.",
        "poster_path": "/AcKVlWaNVVVFQwro3nLXqPljcYA.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          27,
          9648,
          878,
          53
        ]),
        "popularity": "1419.195",
        "release_date": "2022-07-20",
        "vote_average": 7.103,
        "vote_count": 798,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/5FFpcmPzD5mhLom7bymZq7Py8eT.jpg",
        "tmdbid": 862551,
        "title": "Me Time",
        "original_language": "en",
        "overview": "With his family away, a devoted stay-at-home dad enjoys his first me time in years by joining his hard-partying old friend on a wild birthday adventure.",
        "poster_path": "/bkjPoisqAavXUvtoirxTEcLLQyI.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          35
        ]),
        "popularity": "139.203",
        "release_date": "2022-08-26",
        "vote_average": 5.822,
        "vote_count": 104,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/xfNHRI2f5kHGvogxLd0C5sB90L7.jpg",
        "tmdbid": 539681,
        "title": "DC League of Super-Pets",
        "original_language": "en",
        "overview": "When Superman and the rest of the Justice League are kidnapped, Krypto the Super-Dog must convince a rag-tag shelter pack - Ace the hound, PB the potbellied pig, Merton the turtle and Chip the squirrel - to master their own newfound powers and help him rescue the superheroes.",
        "poster_path": "/r7XifzvtezNt31ypvsmb6Oqxw49.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          16,
          28,
          10751,
          878,
          35
        ]),
        "popularity": "3307.165",
        "release_date": "2022-07-27",
        "vote_average": 7.6,
        "vote_count": 231,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/rHzoz94bRfyfNLjiIB26Wt5KDHE.jpg",
        "tmdbid": 773867,
        "title": "Seoul Vibe",
        "original_language": "ko",
        "overview": "Chasing speed, dreams and money, a team of drivers get involved in the slush fund investigation of a powerful figure during the 1988 Seoul Olympics.",
        "poster_path": "/ffX0TL3uKerLXACkuZGWhAPMbAq.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          28,
          80,
          35
        ]),
        "popularity": "112.557",
        "release_date": "2022-08-26",
        "vote_average": 7.7,
        "vote_count": 15,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/9GvhICFMiRQA82vS6ydkXxeEkrd.jpg",
        "tmdbid": 92783,
        "title": "She-Hulk: Attorney at Law",
        "original_language": "en",
        "overview": "Jennifer Walters navigates the complicated life of a single, 30-something attorney who also happens to be a green 6-foot-7-inch superpowered hulk.",
        "poster_path": "/hJfI6AGrmr4uSHRccfJuSsapvOb.jpg",
        "media_type": "tv",
        "genre_ids": JSON.stringify([
          35,
          10765
        ]),
        "popularity": "6653.395",
        "vote_average": 7.435,
        "vote_count": 440,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/jauI01vUIkPA0xVsamGj0Gs1nNL.jpg",
        "tmdbid": 507086,
        "title": "Jurassic World Dominion",
        "original_language": "en",
        "overview": "Four years after Isla Nublar was destroyed, dinosaurs now live—and hunt—alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators on a planet they now share with history’s most fearsome creatures.",
        "poster_path": "/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          12,
          28,
          878
        ]),
        "popularity": "3733.899",
        "release_date": "2022-06-01",
        "vote_average": 7.09,
        "vote_count": 3067,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/wNKwOtq27yfN13SKKV07NwkpBA3.jpg",
        "tmdbid": 80752,
        "title": "See",
        "original_language": "en",
        "overview": "A virus has decimated humankind. Those who survived emerged blind. Centuries later when twins are born with the mythic ability to see, their father must protect his tribe against a threatened queen.",
        "poster_path": "/lKDIhc9FQibDiBQ57n3ELfZCyZg.jpg",
        "media_type": "tv",
        "genre_ids": JSON.stringify([
          18,
          10765,
          10759
        ]),
        "popularity": "468.966",
        "vote_average": 8.247,
        "vote_count": 1698,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/ndAaTYlm9Q106EKJ7ZGRf9nJ4ha.jpg",
        "tmdbid": 990691,
        "original_language": "da",
        "tmdbid": "Kærlighed for voksne",
        "overview": "The thin line between love and hate turns deadly when a wife discovers her husband’s affair — and they both take extreme measures to get what they want.",
        "poster_path": "/hSNHg7qReDtBk1u2PaSSzTTQ8ax.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          53,
          18
        ]),
        "popularity": "74.41",
        "release_date": "2022-08-26",
        "vote_average": 6.1,
        "vote_count": 31,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/7ZO9yoEU2fAHKhmJWfAc2QIPWJg.jpg",
        "tmdbid": 766507,
        "title": "Prey",
        "original_language": "en",
        "overview": "When danger threatens her camp, the fierce and highly skilled Comanche warrior Naru sets out to protect her people. But the prey she stalks turns out to be a highly evolved alien predator with a technically advanced arsenal.",
        "poster_path": "/ujr5pztc1oitbe7ViMUOilFaJ7s.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          53,
          28
        ]),
        "popularity": "6874.014",
        "release_date": "2022-08-02",
        "vote_average": 8.041,
        "vote_count": 3249,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/HNnuIT0waeGwsWqp5v7aSM6NJQ.jpg",
        "tmdbid": 135035,
        "title": "Partner Track",
        "original_language": "en",
        "overview": "Centers on Ingrid Yun, an idealistic young lawyer, struggles with her moral compass and her passions as she fights to climb the partner track at an elite New York City law firm.",
        "poster_path": "/ekb76bz68oSJrbYrDMCYsLI5I6E.jpg",
        "media_type": "tv",
        "genre_ids": JSON.stringify([
          18
        ]),
        "popularity": "83.149",
        "vote_average": 8,
        "vote_count": 10,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/nmGWzTLMXy9x7mKd8NKPLmHtWGa.jpg",
        "tmdbid": 438148,
        "title": "Minions: The Rise of Gru",
        "original_language": "en",
        "overview": "A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enough to join them, with the backup of his followers, the Minions.",
        "poster_path": "/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          16,
          12,
          35,
          14
        ]),
        "popularity": "3747.877",
        "release_date": "2022-06-29",
        "vote_average": 7.719,
        "vote_count": 1665,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/jILeJ60zPpIjjJHGSmIeY4eO30t.jpg",
        "tmdbid": 744,
        "title": "Top Gun",
        "original_language": "en",
        "overview": "For Lieutenant Pete 'Maverick' Mitchell and his friend and co-pilot Nick 'Goose' Bradshaw, being accepted into an elite training school for fighter pilots is a dream come true. But a tragedy, as well as personal demons, will threaten Pete's dreams of becoming an ace pilot.",
        "poster_path": "/xUuHj3CgmZQ9P2cMaqQs4J0d4Zc.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          28,
          18
        ]),
        "popularity": "399.576",
        "release_date": "1986-05-16",
        "vote_average": 7.008,
        "vote_count": 6328,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg",
        "tmdbid": 634649,
        "title": "Spider-Man: No Way Home",
        "original_language": "en",
        "overview": "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
        "poster_path": "/uJYYizSuA9Y3DCs0qS4qWvHfZg4.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          28,
          12,
          878
        ]),
        "popularity": "1570.276",
        "release_date": "2021-12-15",
        "vote_average": 8.046,
        "vote_count": 14850,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/suopoADq0k8YZr4dQXcU6pToj6s.jpg",
        "tmdbid": 1399,
        "title": "Game of Thrones",
        "original_language": "en",
        "overview": "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
        "poster_path": "/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",
        "media_type": "tv",
        "genre_ids": JSON.stringify([
          10765,
          18,
          10759
        ]),
        "popularity": "1247.198",
        "vote_average": 8.421,
        "vote_count": 18689,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/6cpRpfD3isvluFwXDGSiDVyibPJ.jpg",
        "tmdbid": 829560,
        "title": "The Next 365 Days",
        "original_language": "pl",
        "overview": "Laura and Massimo's relationship hangs in the balance as they try to overcome trust issues while a tenacious Nacho works to push them apart.",
        "poster_path": "/dlyzCeI8wojBsUWdkNdO5AXtmZq.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          10749,
          18
        ]),
        "popularity": "2166.868",
        "release_date": "2022-08-19",
        "vote_average": 6.886,
        "vote_count": 312,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/vvObT0eIWGlArLQx3K5wZ0uT812.jpg",
        "tmdbid": 616037,
        "title": "Thor: Love and Thunder",
        "original_language": "en",
        "overview": "After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now inexplicably wields Mjolnir as the Relatively Mighty Girl Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.",
        "poster_path": "/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          28,
          12,
          14
        ]),
        "popularity": "8104.31",
        "release_date": "2022-07-06",
        "vote_average": 6.772,
        "vote_count": 2117,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/9pRCvopXw3RKZtUA7bQvW14v3Kq.jpg",
        "tmdbid": 206910,
        "title": "Ludik",
        "original_language": "en",
        "overview": "To save a kidnapped family member, an enterprising furniture tycoon must use his secret diamond smuggling operation to transport guns across the border.",
        "poster_path": "/pNdYJdE1sSACnjgWjnIJAm7lfiV.jpg",
        "media_type": "tv",
        "genre_ids": JSON.stringify([
          80,
          18
        ]),
        "popularity": "71.246",
        "vote_average": 7.6,
        "vote_count": 9,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/nW5fUbldp1DYf2uQ3zJTUdachOu.jpg",
        "tmdbid": 718789,
        "title": "Lightyear",
        "original_language": "en",
        "overview": "Legendary Space Ranger Buzz Lightyear embarks on an intergalactic adventure alongside a group of ambitious recruits and his robot companion Sox.",
        "poster_path": "/ox4goZd956BxqJH6iLwhWPL9ct4.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          16,
          878,
          12,
          28,
          10751
        ]),
        "popularity": "1754.245",
        "release_date": "2022-06-15",
        "vote_average": 7.3,
        "vote_count": 1876,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/hYC6uetTLSqbLZ3dFY0IfXWhl93.jpg",
        "tmdbid": 37854,
        "title": "One Piece",
        "original_language": "ja",
        "overview": "Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous \"One Piece\" behind. Whoever claims the \"One Piece\" will be named the new King of the Pirates. Monkey D. Luffy, a boy who consumed a \"Devil Fruit,\" decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he's surrounded by a bevy of skilled fighters and thieves to help him along the way. Luffy will do anything to get the One Piece and become King of the Pirates!",
        "poster_path": "/fcXdJlbSdUEeMSJFsXKsznGwwok.jpg",
        "media_type": "tv",
        "genre_ids": JSON.stringify([
          10759,
          35,
          16
        ]),
        "popularity": "131.44",
        "vote_average": 8.768,
        "vote_count": 3169,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/eW5UazRUpGL2lv0GNG17Cpd37li.jpg",
        "tmdbid": 1005835,
        "title": "That's Amor",
        "original_language": "en",
        "overview": "After her job and relationship implode on the same day, Sofia starts from scratch — and meets a dashing Spanish chef who might be her missing ingredient.",
        "poster_path": "/iyYibVfi8q0zwsX1evl7mxTZJp1.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          10749,
          35
        ]),
        "popularity": "107.565",
        "release_date": "2022-08-25",
        "vote_average": 4.2,
        "vote_count": 13,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/wDyM1lIIgK4RIDAgr8iuZe9N1cf.jpg",
        "tmdbid": 755566,
        "title": "Day Shift",
        "original_language": "en",
        "overview": "An LA vampire hunter has a week to come up with the cash to pay for his kid's tuition and braces. Trying to make a living these days just might kill him.",
        "poster_path": "/bI7lGR5HuYlENlp11brKUAaPHuO.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          28,
          14,
          27,
          35
        ]),
        "popularity": "2915.738",
        "release_date": "2022-08-10",
        "vote_average": 6.886,
        "vote_count": 729,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/pdfCr8W0wBCpdjbZXSxnKhZtosP.jpg",
        "tmdbid": 84773,
        "title": "The Lord of the Rings: The Rings of Power",
        "original_language": "en",
        "overview": "Beginning in a time of relative peace, we follow an ensemble cast of characters as they confront the re-emergence of evil to Middle-earth. From the darkest depths of the Misty Mountains, to the majestic forests of Lindon, to the breathtaking island kingdom of Númenor, to the furthest reaches of the map, these kingdoms and characters will carve out legacies that live on long after they are gone.",
        "poster_path": "/suyNxglk17Cpk8rCM2kZgqKdftk.jpg",
        "media_type": "tv",
        "genre_ids": JSON.stringify([
          10765,
          10759,
          18
        ]),
        "popularity": "421.634",
        "vote_average": 7.8,
        "vote_count": 5,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/wcKFYIiVDvRURrzglV9kGu7fpfY.jpg",
        "tmdbid": 453395,
        "title": "Doctor Strange in the Multiverse of Madness",
        "original_language": "en",
        "overview": "Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.",
        "poster_path": "/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          14,
          28,
          12
        ]),
        "popularity": "1863.111",
        "release_date": "2022-05-04",
        "vote_average": 7.498,
        "vote_count": 5491,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/xyS0NgcQ2pbGWcwvSSu3xKEBhoO.jpg",
        "tmdbid": 614934,
        "title": "Elvis",
        "original_language": "en",
        "overview": "The life story of Elvis Presley as seen through the complicated relationship with his enigmatic manager, Colonel Tom Parker.",
        "poster_path": "/qBOKWqAFbveZ4ryjJJwbie6tXkQ.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          10402,
          18,
          36
        ]),
        "popularity": "697.476",
        "release_date": "2022-06-22",
        "vote_average": 7.909,
        "vote_count": 1245,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/eqhKMZTLcieAvoH6CBqknTTfNby.jpg",
        "tmdbid": 90802,
        "title": "The Sandman",
        "original_language": "en",
        "overview": "After years of imprisonment, Morpheus — the King of Dreams — embarks on a journey across worlds to find what was stolen from him and restore his power.",
        "poster_path": "/q54qEgagGOYCq5D1903eBVMNkbo.jpg",
        "media_type": "tv",
        "genre_ids": JSON.stringify([
          10765,
          18
        ]),
        "popularity": "2058.334",
        "vote_average": 8.247,
        "vote_count": 596,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/ugS5FVfCI3RV0ZwZtBV3HAV75OX.jpg",
        "tmdbid": 610150,
        "title": "Dragon Ball Super: Super Hero",
        "original_language": "ja",
        "overview": "The Red Ribbon Army, an evil organization that was once destroyed by Goku in the past, has been reformed by a group of people who have created new and mightier Androids, Gamma 1 and Gamma 2, and seek vengeance against Goku and his family.",
        "poster_path": "/rugyJdeoJm7cSJL1q4jBpTNbxyU.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          16,
          878,
          28
        ]),
        "popularity": "7517.196",
        "release_date": "2022-06-11",
        "vote_average": 7.121,
        "vote_count": 203,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/5GA3vV1aWWHTSDO5eno8V5zDo8r.jpg",
        "tmdbid": 760161,
        "title": "Orphan: First Kill",
        "original_language": "en",
        "overview": "After escaping from an Estonian psychiatric facility, Leena Klammer travels to America by impersonating Esther, the missing daughter of a wealthy family. But when her mask starts to slip, she is put against a mother who will protect her family from the murderous “child” at any cost.",
        "poster_path": "/wSqAXL1EHVJ3MOnJzMhUngc8gFs.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          27,
          53
        ]),
        "popularity": "1210.144",
        "release_date": "2022-07-27",
        "vote_average": 7.215,
        "vote_count": 331,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/fX3tu1w7iZJVP91bNvocmisOfWD.jpg",
        "tmdbid": 838197,
        "title": "Watch Out, We're Mad",
        "original_language": "it",
        "overview": "Carezza and Sorriso, brothers very different from each other and in quarrel since childhood, will have to put aside their controversies to recover the legendary Dune Buggy, once belonged to their beloved father and now stolen from him by Torsillo, an unscrupulous building speculator, and his son Raniero. In doing so, they will forge an unusual alliance with a circus community, headed by the beautiful and dangerous Miriam and threatened by Torsillo's dirty business. Between daring chases, memorable fights and delicate meals based on beer and sausages, will the two brothers be able to find their beloved car?",
        "poster_path": "/qlrRi05x5hjoM29hz6TDLGTUSop.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          35,
          28
        ]),
        "popularity": "17.952",
        "release_date": "2022-03-23",
        "vote_average": 4.7,
        "vote_count": 46,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/C8FpZfTPEZDjngPlatiFsaDB4A.jpg",
        "tmdbid": 718930,
        "title": "Bullet Train",
        "original_language": "en",
        "overview": "Unlucky assassin Ladybug is determined to do his job peacefully after one too many gigs gone off the rails. Fate, however, may have other plans, as Ladybug's latest mission puts him on a collision course with lethal adversaries from around the globe—all with connected, yet conflicting, objectives—on the world's fastest train.",
        "poster_path": "/tVxDe01Zy3kZqaZRNiXFGDICdZk.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          28,
          35,
          80
        ]),
        "popularity": "911.381",
        "release_date": "2022-07-03",
        "vote_average": 7.462,
        "vote_count": 540,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg",
        "tmdbid": 414906,
        "title": "The Batman",
        "original_language": "en",
        "overview": "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.",
        "poster_path": "/74xTEgt7R36Fpooo50r9T25onhq.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          80,
          9648,
          53
        ]),
        "popularity": "861.624",
        "release_date": "2022-03-01",
        "vote_average": 7.746,
        "vote_count": 6022,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/nZiViOq69784a4CDr2Hn5IqERjE.jpg",
        "tmdbid": 93166,
        "title": "The Capture",
        "original_language": "en",
        "poster_path": "/3JDXPHPxX5ugSNLy6yNEpSSP4Qf.jpg",
        "media_type": "tv",
        "genre_ids": JSON.stringify([
          80,
          18
        ]),
        "popularity": "84.011",
        "vote_average": 7.849,
        "vote_count": 119,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/8TUb2U9GN3PonbXAQ1FBcJ4XeXu.jpg",
        "tmdbid": 760741,
        "title": "Beast",
        "original_language": "en",
        "overview": "A recently widowed man and his two teenage daughters travel to a game reserve in South Africa. However, their journey of healing soon turns into a fight for survival when a bloodthirsty lion starts to stalk them.",
        "poster_path": "/xIGr7UHsKf0URWmyyd5qFMAq4d8.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          53
        ]),
        "popularity": "759.843",
        "release_date": "2022-08-11",
        "vote_average": 6.4,
        "vote_count": 62,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/yaze6df9AMIA9oeDEbIZ4zOTRCJ.jpg",
        "tmdbid": 960700,
        "title": "Fullmetal Alchemist the Revenge of Scar",
        "original_language": "ja",
        "overview": "The Elric brothers meet their toughest opponent yet — a lone serial killer with a large scar on his forehead.",
        "poster_path": "/14lQfkLDgEIrEtyUMfj5rJEKVlS.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          28,
          12,
          14
        ]),
        "popularity": "173.515",
        "release_date": "2022-05-20",
        "vote_average": 6.7,
        "vote_count": 29,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/8f2JboeqPuSepNVQJUGttvnqgkl.jpg",
        "tmdbid": 156935,
        "title": "Lost Ollie",
        "original_language": "en",
        "overview": "A patchwork rabbit with floppy ears and fuzzy memories embarks on an epic quest to find his best friend — the young boy he desperately loves.",
        "poster_path": "/kwx40ip5Yq24faboIBu3BaICaJa.jpg",
        "media_type": "tv",
        "genre_ids": JSON.stringify([
          16,
          10751,
          18
        ]),
        "popularity": "68.446",
        "vote_average": 8.5,
        "vote_count": 11,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/AfvIjhDu9p64jKcmohS4hsPG95Q.jpg",
        "tmdbid": 756999,
        "title": "The Black Phone",
        "original_language": "en",
        "overview": "Finney Blake, a shy but clever 13-year-old boy, is abducted by a sadistic killer and trapped in a soundproof basement where screaming is of little use. When a disconnected phone on the wall begins to ring, Finney discovers that he can hear the voices of the killer’s previous victims. And they are dead set on making sure that what happened to them doesn’t happen to Finney.",
        "poster_path": "/lr11mCT85T1JanlgjMuhs9nMht4.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          27,
          53,
          14
        ]),
        "popularity": "2851.056",
        "release_date": "2022-06-22",
        "vote_average": 7.942,
        "vote_count": 2184,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/pj3zCnPXI5Bh3lblZAgfzWUAn5v.jpg",
        "tmdbid": 135157,
        "title": "Alchemy of Souls",
        "original_language": "ko",
        "overview": "A powerful sorceress in a blind woman's body encounters a man from a prestigious family, who wants her help to change his destiny.",
        "poster_path": "/q2IiPRSXPOZ6qVRj36WRAYEQyHs.jpg",
        "media_type": "tv",
        "genre_ids": JSON.stringify([
          18,
          10759,
          9648,
          10765
        ]),
        "popularity": "301.139",
        "vote_average": 8.7,
        "vote_count": 29,
        "created_at": new Date(),
      },
      {
        "backdrop_path": "/jII9mJZ4EWAodGIhALpBPc6MuPB.jpg",
        "tmdbid": 1005342,
        "title": "Running with the Devil: The Wild World of John McAfee",
        "original_language": "en",
        "overview": "Through raw, revealing footage and interviews with fugitive tech pioneer John McAfee, this documentary uncovers new layers of his wild years on the run.",
        "poster_path": "/jcCPTtnBj9W52d97QyO9X6Xxfg7.jpg",
        "media_type": "movie",
        "genre_ids": JSON.stringify([
          99
        ]),
        "popularity": "179.913",
        "release_date": "2022-08-24",
        "vote_average": 7.357,
        "vote_count": 14,
        "created_at": new Date(),
      }
  ]);
};
